apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-06-13T14:24:34Z"
  labels:
    app: nginx
    tier: frontend
  name: nginx
  namespace: default
  resourceVersion: "62410"
  uid: 58813d09-0021-43a7-9169-4dd7641121d0
spec:
  clusterIP: 10.108.233.186
  clusterIPs:
  - 10.108.233.186
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
