apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restapi-ingress
  namespace: restapi
spec:
  ingressClassName: nginx-example
  rules:
  - http:
      paths:
        - pathType: Prefix
          path: /apis/
          backend:
            service:
              name: restapi
              port:
                number: 9090
            
    