apiVersion: v1
kind: Pod
metadata:
    creationTimestamp: null
    labels:
      run: lib
    name: lib
    namespace: pod
spec:
  imagePullSecrets:
  - name: pullsecret
  containers:
  - name: myfirstcontainer
    image: priya989/dockerpull:latest
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy:  Always
status: {}